In [2]:
import numpy as np

# Question 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [3]:
a=np.arange(2,51,3)

In [4]:
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2:
Accept two lists of 5 elements each from the user.<br>
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [5]:
print("Enter 5 numbers for list one: ")
l1=np.array([int(input()) for i in range(5)])
print("\nEnter 5 numbers for list two: ")
l2=np.array([int(input()) for i in range(5)])
l3=np.concatenate([l1,l2])
print('\n',l3,'\n',sep='')
print(np.sort(l1),'\n',np.sort(l2),'\n',np.sort(l3),sep='')

Enter 5 numbers for list one: 
1
3
5
7
9

Enter 5 numbers for list two: 
2
4
6
8
10

[ 1  3  5  7  9  2  4  6  8 10]

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


# Question 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [9]:
lst=np.arange(24).reshape(3,4,2)
print(lst,'\n')
print(type(lst),lst.shape,sep='\n')
print('Dimensions: ', np.ndim(lst))
print('Size of ndarray: ',np.size(lst))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]] 

<class 'numpy.ndarray'>
(3, 4, 2)
Dimensions:  3
Size of ndarray:  24


# Question 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet<br>
Hint: np.newaxis, np.expand_dims

In [13]:
# Creating a 1D array
lst1 = np.arange(10)
print(lst1.shape)

# Converting the 1D array to 2D array by inserting an axis at position 1
lst2 = np.expand_dims(lst1, axis=1)
print(lst2.shape)


# Converting the 1D array to 2D array by inserting an axis at position 0
lst3 = np.expand_dims(lst1, axis=0)
print(lst3.shape)

# Converting the 1D array to 3D array by inserting an axis at position 1,2
lst4=np.expand_dims(lst1,axis=(1,2))
print(lst4.shape)

# creating a 2D array
lst5= np.arange(25).reshape(5,5)
print(lst5.shape)

# Converting above 2D array to 3D array by inserting an axis at position 1
lst6 = np.expand_dims(lst5, axis=1)
print(lst6.shape)

(10,)
(10, 1)
(1, 10)
(10, 1, 1)
(5, 5)
(5, 1, 5)


# Question 5:
Consider two square numpy arrays. Stack them vertically and horizontally.<br>
Hint: Use vstack(), hstack()

In [16]:
lst1=np.arange(16).reshape(4,4)
lst2=np.arange(16,32).reshape(4,4)

print(np.vstack((lst1,lst2)))
print()
print(np.hstack((lst1,lst2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]


# Question 6:
How to get unique items and counts of unique items?

In [19]:
lst11 = np.array([[1,2,2,3,5],[5,6,10,7,8],[8,9,10,1,10]])

uniq,count= np.unique(lst11,return_counts=True)
print(uniq)
print(count)

[ 1  2  3  5  6  7  8  9 10]
[2 2 1 2 1 1 2 1 3]
